name: Docker Image CI

on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Event Information
      run: |
        echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"

    # - uses: actions/checkout@v2
    # - name: Build and Publish a Docker image
    #   env:
    #     DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    #   run: |
    #     docker build . --file Dockerfile --tag msrband/rails-test
    #     docker login --username msrband --password $DOCKER_HUB_ACCESS_TOKEN && docker push msrband/rails-test
